// Aliases oficiais dos tribunais na API Pública do DataJud (CNJ)
// Fonte: https://datajud-wiki.cnj.jus.br/api-publica/endpoints
module.exports = {
  "Tribunais Superiores": {
    api_publica_tst: "Tribunal Superior do Trabalho",
    api_publica_tse: "Tribunal Superior Eleitoral",
    api_publica_stj: "Superior Tribunal de Justiça",
    api_publica_stm: "Superior Tribunal Militar",
  },
  "Justiça Federal": {
    api_publica_trf1: "Tribunal Regional Federal da 1ª Região",
    api_publica_trf2: "Tribunal Regional Federal da 2ª Região",
    api_publica_trf3: "Tribunal Regional Federal da 3ª Região",
    api_publica_trf4: "Tribunal Regional Federal da 4ª Região",
    api_publica_trf5: "Tribunal Regional Federal da 5ª Região",
    api_publica_trf6: "Tribunal Regional Federal da 6ª Região",
  },
  "Justiça Estadual": {
    api_publica_tjac: "Tribunal de Justiça do Acre",
    api_publica_tjal: "Tribunal de Justiça de Alagoas",
    api_publica_tjam: "Tribunal de Justiça do Amazonas",
    api_publica_tjap: "Tribunal de Justiça do Amapá",
    api_publica_tjba: "Tribunal de Justiça da Bahia",
    api_publica_tjce: "Tribunal de Justiça do Ceará",
    api_publica_tjdft: "TJ do Distrito Federal e Territórios",
    api_publica_tjes: "Tribunal de Justiça do Espírito Santo",
    api_publica_tjgo: "Tribunal de Justiça do Goiás",
    api_publica_tjma: "Tribunal de Justiça do Maranhão",
    api_publica_tjmg: "Tribunal de Justiça de Minas Gerais",
    api_publica_tjms: "TJ do Mato Grosso do Sul",
    api_publica_tjmt: "Tribunal de Justiça do Mato Grosso",
    api_publica_tjpa: "Tribunal de Justiça do Pará",
    api_publica_tjpb: "Tribunal de Justiça da Paraíba",
    api_publica_tjpe: "Tribunal de Justiça de Pernambuco",
    api_publica_tjpi: "Tribunal de Justiça do Piauí",
    api_publica_tjpr: "Tribunal de Justiça do Paraná",
    api_publica_tjrj: "Tribunal de Justiça do Rio de Janeiro",
    api_publica_tjrn: "TJ do Rio Grande do Norte",
    api_publica_tjro: "Tribunal de Justiça de Rondônia",
    api_publica_tjrr: "Tribunal de Justiça de Roraima",
    api_publica_tjrs: "Tribunal de Justiça do Rio Grande do Sul",
    api_publica_tjsc: "Tribunal de Justiça de Santa Catarina",
    api_publica_tjse: "Tribunal de Justiça de Sergipe",
    api_publica_tjsp: "Tribunal de Justiça de São Paulo",
    api_publica_tjto: "Tribunal de Justiça do Tocantins",
  },
  "Justiça do Trabalho": Object.fromEntries(
    Array.from({ length: 24 }, (_, i) => [
      `api_publica_trt${i + 1}`,
      `Tribunal Regional do Trabalho da ${i + 1}ª Região`,
    ])
  ),
  "Justiça Eleitoral": {
    "api_publica_tre-ac": "Tribunal Regional Eleitoral do Acre",
    "api_publica_tre-al": "Tribunal Regional Eleitoral de Alagoas",
    "api_publica_tre-am": "Tribunal Regional Eleitoral do Amazonas",
    "api_publica_tre-ap": "Tribunal Regional Eleitoral do Amapá",
    "api_publica_tre-ba": "Tribunal Regional Eleitoral da Bahia",
    "api_publica_tre-ce": "Tribunal Regional Eleitoral do Ceará",
    "api_publica_tre-dft": "Tribunal Regional Eleitoral do Distrito Federal",
    "api_publica_tre-es": "Tribunal Regional Eleitoral do Espírito Santo",
    "api_publica_tre-go": "Tribunal Regional Eleitoral do Goiás",
    "api_publica_tre-ma": "Tribunal Regional Eleitoral do Maranhão",
    "api_publica_tre-mg": "Tribunal Regional Eleitoral de Minas Gerais",
    "api_publica_tre-ms": "Tribunal Regional Eleitoral do Mato Grosso do Sul",
    "api_publica_tre-mt": "Tribunal Regional Eleitoral do Mato Grosso",
    "api_publica_tre-pa": "Tribunal Regional Eleitoral do Pará",
    "api_publica_tre-pb": "Tribunal Regional Eleitoral da Paraíba",
    "api_publica_tre-pe": "Tribunal Regional Eleitoral de Pernambuco",
    "api_publica_tre-pi": "Tribunal Regional Eleitoral do Piauí",
    "api_publica_tre-pr": "Tribunal Regional Eleitoral do Paraná",
    "api_publica_tre-rj": "Tribunal Regional Eleitoral do Rio de Janeiro",
    "api_publica_tre-rn": "Tribunal Regional Eleitoral do Rio Grande do Norte",
    "api_publica_tre-ro": "Tribunal Regional Eleitoral de Rondônia",
    "api_publica_tre-rr": "Tribunal Regional Eleitoral de Roraima",
    "api_publica_tre-rs": "Tribunal Regional Eleitoral do Rio Grande do Sul",
    "api_publica_tre-sc": "Tribunal Regional Eleitoral de Santa Catarina",
    "api_publica_tre-se": "Tribunal Regional Eleitoral de Sergipe",
    "api_publica_tre-sp": "Tribunal Regional Eleitoral de São Paulo",
    "api_publica_tre-to": "Tribunal Regional Eleitoral do Tocantins",
  },
  "Justiça Militar": {
    api_publica_tjmmg: "Tribunal de Justiça Militar de Minas Gerais",
    api_publica_tjmrs: "Tribunal de Justiça Militar do Rio Grande do Sul",
    api_publica_tjmsp: "Tribunal de Justiça Militar de São Paulo",
  },
};
